#! /usr/bin/env ruby

require 'rubygems'
require 'net/scp'
class Sod
  def self.bootstrap(ip_address)
    puts "need password"
    password = $stdin.gets
    Net::SSH.start(ip_address, "root", :password => password.strip) do |connection|
      scp = Net::SCP.new connection
      scp.upload! File.join(File.dirname(__FILE__), "rvm_install.sh"), "/root/"
      puts connection.exec! 'rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-4.noarch.rpm'
      puts "Installing git and c"
      puts connection.exec! "yum -y install git gcc automake autoconf libtool make"
      rvm(connection)
      repo_destination = '/usr/local/app/'
      puts connection.exec! "mkdir -p #{repo_destination}"
      repo_name = "diaspora"
      clone_repo!(connection, "git://github.com/diaspora/#{repo_name}.git", "#{repo_destination}")
      puts connection.exec! "mkdir -p /etc/chef && echo 'cookbook_path \"#{repo_destination + repo_name}/chef/cookbooks\"' > /etc/chef/solo.rb"
      puts rvm_command! connection, "chef-solo -j #{repo_destination + repo_name}/chef/cookbooks/bootstrap/bootstrap.json"
      puts rvm_command! connection, "cd #{repo_destination}diaspora && bundle install"
    end
  end
  def self.rvm(connection)
      puts "installing rvm"
      puts connection.exec! "bash /root/rvm_install.sh"
      puts connection.exec! "rvm package install zlib"
      puts connection.exec! "rvm package install openssl"
      puts connection.exec! "rvm package install readline"
      puts connection.exec! "rvm install 1.8.7 -C --with-zlib-dir=/usr/local/rvm/usr --with-readline-dir=/usr/local/rvm/usr --with-openssl-dir=/usr/local/rvm/usr"
      puts 'setting /etc/bashrc'
      puts connection.exec! %{grep -q rvm /etc/bashrc || echo '[[ -s "/usr/local/lib/rvm" ]] && . "/usr/local/lib/rvm"' >> /etc/bashrc}
  end
  def self.install_chef(connection)
      puts "installing bundler"
      puts rvm_command! connection, "gem install bundler"
      puts connection.exec! "mkdir -p /chef"
      puts "uploading Gemfile for chef"
      scp.upload File.join(File.dirname(__FILE__), "chef_Gemfile"), "/chef/Gemfile"
      puts rvm_command! connection, "cd /chef && bundle install"
  end
  def self.rvm_command!(connection, string)
    command = "sh -cl 'bash /usr/local/lib/rvm && rvm use 1.8.7 && #{string}'"
    puts "Executing RVM command #{command}"
    connection.exec! command
  end

  def self.clone_repo!(connection, repo_location, destination)
    puts connection.exec! "rm -rf /usr/local/app/diaspora"
    puts connection.exec! "cd #{destination} && git clone #{repo_location}"
  end
end

puts "need an ip address" unless ARGV
Sod.bootstrap(ARGV[0])
